### ISSUE TITLE
Dummy entry generator

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#10]
Produce control (separate back-end & fore-end components) that can generate dummy narrative entries.

UI control should support:

* on/off
* rate of generation (1x, 5x, 10x,  20x per 5 secs)
* bulk injection (50, 500, 5000)
* display of current time (if time is accelerated it will effectively move into the future)

The UI definition file includes a list of categories, the entries in those categories, and the fields in those entries.

Different types of entry occur at different frequencies.  I suggest I/we add an "interval" field to the UI definition for each entry. This will be the number of seconds between when this entry type typically happens.  Then, when running forward in accelerated mode the generator knows when to inject which one.

Some initial interval thoughts would be:
* CO Comment: 30 minutes
* Maneouvre: 10 mins
* New underwater contact: one hour

**Comment by Morphexe** [comment]
@IanMayo I have tackled this issue as a starting point.
I created a class that handles this, the only thing we need to discuss is how to handle the future time since the createAt is done by the Redux Action.

Currently, it creates all entries types with randomized interval - if we go forward with the intervals on the config, it should be very straightforward to change.

It still needs some touches though, its only generating text fields with the "dummy" placeholder, since I wasn't sure if this is exactly what you want.

The front end UI, I haven't touched, since like I said, I am not sure how you want to tackled my current solution

**Comment by IanMayo** [comment]
@Morphexe - thanks for the progress.

Strategies for time:
1.  We could use a starting time several days ago
2.  We could introduce a "Time now" datastore object.  As the generator moves into the future it updates the value of **timeNow**.  When we're doing a filter for *Show entries in the last 5 minutes*, it uses **timeNow** instead of **new Date()** for the comparison.

Strategies for populating the fields.  I suggest we introduce a new field to the form-field (& validator) types, that creates a random valid value for that field type.  For text it would be lorem, for *Angle* it would be 0..360.

**Comment by Morphexe** [comment]
I belive this is finished.
