### ISSUE TITLE
New events don't have color property

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#107]
Events that come from the generator have the correct coloured border in the EntryList

When they come from the event buttons they don't have the color.

Yes, this was probably list during a merge conflicts operation.

**Comment by Morphexe** [comment]
@IanMayo  Actualy the way color coding is working is not the best, we should load colors from the config file, not assign them on a per entry basis, this is extremely error-prone. And won't allow the user to change color scheme via the config file (since old events would use the wrong color), not sure if a requirement.

The issue is fixed, but it might need revisiting.

**Comment by IanMayo** [comment]
i thought we did load them from the config file, they're in the Category element, aren't they?

**Comment by Morphexe** [comment]
@IanMayo What I am saying is that when entry is generated we are currently assigning them a color.
So they stored that color in the database. IMO this shouldn't happen like this, its fated to fail. We should instead create a method that given an entry category, it searches the current config and loads the color.
If that feels like what you want, I will tackle this.

**Comment by IanMayo** [comment]
Ok. Let's not worry about it for this version.
