### ISSUE TITLE
Inline forms

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#17]
We wish users to be able to edit entries inline.

Catch double-click, and switch that row to an inline form. 

Start off with date-time, privacy, type, comment

Here's a previous version, from years ago:
http://taskmgtsystem.com/diary3/GWTDiary.html

Instructions:
* Select *Create new* tab, then *Create lake*
* Select items from the top menu. Each one inserts a blank entry.  Fill in some fields, then press OK.
* Select *Utilities* / *Generate 50*
* Now double-click on some entries, to edit them
* Select *Filter* / *Filter*. Now try to apply some filters.

## Implementation thoughts
Suspect we could use a **state** property for an entry. This will move through:
* empty
* started
* complete

When a button has been clicked, it will dispatch an entry with the correct fields, but with a state of **empty**. This inserts an inline form.  Once the user started editing, but it's still unvalidated (missing fields) then it becomes **started**. The user can click "Save draft" to collapse the editor, but some decoration shows it's still incomplete. Once the user has double-clicked to open it, complete the fields. and it's validated, and the user presses **Ok**, it changes to **Complete**.

##Note: @Morphexe has implemented a quick version of data editing via popup forms.  It *may* be worth doing A/B testing to see if my users prefer and inline form or a popup dialog.  So, I suspect we should have a **feature toggle** somewhere that decides if to use an inline form (within the diary listing), or popup forms.  The popup would appear both when first generating the entry, and when double-clicking on an entry in the listing.

**Comment by Morphexe** [comment]
@IanMayo  I was about to tackle this issue, but I realized something, this is already done, only the double click feature is missing, we can reuse the modal I used, but displaying it inline.

My logic is like this : 
OnDblClick -> Expand the view -> show the form inlined (Reuse the modal body) -> the rest is just the same, the only change I can see needing to be done is in the reducer, where instead of appending, we check if an entry has ID before, if it has, then we just update it, else append a new one to the array.
And eventually, if you want to remove the modal altogether, we just change the modal code to create a dummy entry.

We can also reuse the modal idea, to onDblClick show the modal again with the current entry, and edit that from there, which is even easier to do.

**Comment by IanMayo** [comment]
Your strategy is ok.  But, I'd like us to work with a much more compressed version.  There isn't room in the listing for many dialogs (the user may have several open).

But, I'm sure that's just a styling issue.   @Morphexe - if you develop the proof-of-concept, another developer can work on the more compact display.
