### ISSUE TITLE
Introduce Viewer element

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#37]
In addition to the Categories taking lots of buttons in the UI definition, we should also be able to specify the inclusion of small Viewer Widgets.

One of these could be an arrow showing the current course, with the current speed written beneath it.

So, we'll have to modify the UI schema to allow this, and then define the control.  I'm pretty sure the **anyOf** operator will allow us to provide one element "or" he other.  But, I'm battling with this. So, I'm trying to find some extra help via UpWork.

We'll also have to create a UI component for it, which will listen for new course-change events.

**Comment by Morphexe** [comment]
I am not sure what you are trying to accomplish here if what you want is instead of a button to render something else, that's straightforward to implement, the hardest part is the auto-update features since we need to know where we get this information from.

For example, when I rendering the categories entries, I can check for a property that says if its a button or widget of sorts, if its a widget, I skip the button drawing and render the component. Now, getting the data to that component could be achieved via some other extra parameters, for example, an API URL, and the component would be responsible for auto-updating.

@IanMayo  let me hear your thoughts on this.

**Comment by IanMayo** [comment]
Morning @Morphexe,
the data for these viewers comes from within the app. 

The viewer will register for a particular type of entry (or entries) - such as **manoeuvre**.  Then, when one of these is entered Redux (I guess) will pass it onto the viewer.  In this way, a *Course-speed indicator* always knows the current course.
